### ISSUE TITLE
New Stations & Schedules - Light Rail Extension opens Friday, March 16

### ISSUE THREAD

**Issue by brandonfancher** [brandonfancher/charlotte-lightrail#9]
- [x] Get new stations and schedules
- [x] Add to new JSON file (if we're not using Tim's automatic scraper by then)
- [x] Release this update in the app store ASAP

**Comment by TimJohnson** [comment]
Got the updated schedule/map in a PR.  Didn't implement the switch due to time.

**Comment by brandonfancher** [comment]
Done and submitted to the app store!
